### PR TITLE
Updating capec_introduction Notebook

### PR DESCRIPTION
**Pull request by mcheng42**
Updated script to count field frequencies.  Added column on field description table linking to a CAPEC entry where each field is used.  Also worked out the logic for counting co-occurrence frequencies of field pairs.  Formatting the output will be worked on the the future.

### CODE REVIEW

**Review by carlosparadis — COMMENTED** [review]
@mcheng42 bad commit label! I will let this one slide, but please be careful on the following ones! This doesn't really say anything about the commit.

**Review by carlosparadis — CHANGES_REQUESTED** [review]
@mcheng42 Actually, I will have to refuse this request until you do a tiny fix! :-( 

Under the parsing XML header, can you remove that print? Either you provide a sample of how the data looks like, or remove it entirely. That is eating too much space of the notebook, and clearly, no one will read that entire thing. Please let me know if you think otherwise! If you decide to remove it, leave the print commented as a reminder someone can debug using it. 

Make this next commit label more meaningful too, please!

**Comment by mcheng42** [comment]
Applied changes and also included the screenshot of the Description field exception case like you asked during the meeting.  I'll make sure to commit with more meaningful labels in the future, though I'm not sure what the optimal balance is between the label and the description.

**Review by carlosparadis — CHANGES_REQUESTED** [review]
Commit label is good, but it seems you broke something more beyond the print in this commit:

```

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-afb6584d54d8> in <module>()
      2 search = {}
      3 
----> 4 for keys in frequencies:
      5     search[keys] = {}
      6     for key in frequencies:

NameError: name 'frequencies' is not define
```

See at the bottom of the Notebook you just sent me!

**Review by carlosparadis — APPROVED** [review]
@mcheng42 Looks safe now :-) Thanks. I would recommend you send me a note on Trello concerning what is your intended code doing the co-occurrence frequency analysis before you implement the whole thing, it may save you time to discuss it then go all the way through and later have to edit. Your call! I am merging this current version into perceive main repo on the meantime. Thanks!

**Pull request merged**
