### PR TITLE
Merge the sessions and click logs (feature 1)

### PR DESCRIPTION
**Pull request by KarishmaGhiya**

### CODE REVIEW

**Review by carlosparadis — CHANGES_REQUESTED** [review]
@KarishmaGhiya I need the website to stay at the right place in the repository. You are specifying the path to be on the older folder organization. Can you align the folder names to your pull request so I can accept it?

**Comment by KarishmaGhiya** [comment]
I am not sure how to do that..I thought pulling and merge would do the trick.

**Comment by carlosparadis** [comment]
@KarishmaGhiya you guys going to kill me one of these days :-) did you try `git mv new_folder/new_folder2_/blablablabla/folder_old_name new_folder4/new_folder3_/blablablabla2/folder_new_name` as you would using the usual mv command on a terminal? If not, try to google the command `git mv` for some examples. This is much easier than what you sent on this pull request, trust me!

**Comment by carlosparadis** [comment]
I'm accepting this since some files were lost on the original repo and we don't want to lose 2 weeks worth of work!

**Pull request merged**
