### PR TITLE
Crawler code

### PR DESCRIPTION
**Pull request by Karthik7417**
Renamed the crawler script.
Added example line to crawler readme

### CODE REVIEW

**Comment by carlosparadis** [comment]
- Needs to rename file crawler to be more meaningful.
- Add 1 line example of how to run on readme.

**Comment by carlosparadis** [comment]
@Karthik7417 Needs to parameterize the script. Hardcoded won't do.

**Comment by carlosparadis** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5d3OYx0h&#x2F;2-week-1-karthik-fd-crawler-and-fd-corpus"> Week 1 - Karthik - FD Crawler and FD Corpus</a>

**Comment by carlosparadis** [comment]
@Karthik7417 Seems to be a bug on where entire files are left blank. Please see Ira remarks:

> I unpacked the corpus and made a txt file for each year available on Leximancer except for the year 2012. Many of the txt files for this year were empty including many of the texts in the month of April and all the text files for the months of May, June, July, August, September, October, November and December.

Can you check this after you're done with this week tasks?

**Comment by Karthik7417** [comment]
Updated user prompts and default parameters. Code is easier to execute now.

**Pull request merged**
