### PR TITLE
Updated README file

### PR DESCRIPTION
**Pull request by paldosh**
contains instructions for running the revised version of gensim-lda script.

### CODE REVIEW

**Comment by carlosparadis** [comment]
@paldosh I see the request to change the readme file, but where is the script v2?

**Comment by paldosh** [comment]
I am unable to upload it

**Comment by carlosparadis** [comment]
@paldosh What error do you get? Karthik reported something similar.

**Comment by paldosh** [comment]
it says I donot have the permission to upload any file directly to this repository.

**Comment by carlosparadis** [comment]
@paldosh hold on let me try something

**Comment by carlosparadis** [comment]
@paldosh try now Pal.

**Comment by carlosparadis** [comment]
@paldosh Guess it worked. However this is too much permission power to setup (it basically sets everyone as a comitter who can just do merges by themselves). I guess I will need to play around later on how to only allow Pull Requests. I will try running your v2 :-) Thanks for following up on this!

**Pull request merged**
