### PR TITLE
Tracking of Box resizing and Bar Relative Position

### PR DESCRIPTION
**Pull request by KarishmaGhiya**
update my forked branch

### CODE REVIEW

**Comment by carlosparadis** [comment]
@KarishmaGhiya sorry I am not sure what I am merging here so I can't proceed. Can you clarify?

**Comment by KarishmaGhiya** [comment]
@carlosviansi 
My forked branch that is there has to be in synchronization with the original dsel repo. So now the pull request I have made is to merge and update my forked branch and keep it updated with the dsel/perceive. 

On the other hand,  you remember I had cloned a repository Perceive3 from the original dsel /perceive.git onto my local system that day? I have made my changes of feature 2 and 3 to that folder on my local computer. Since i cannot directly be pushing commits made on this local repository to the original dsel one. So after I have my forked branch, I'll copy my changes from Perceive3 on my local computer onto the perceive folder on my local computer, commit and push these changes on my forked branch and then again send u another pull request to add the commit related to Feature 2 on the dsel/perceive. Right?

**Comment by carlosparadis** [comment]
@KarishmaGhiya I see there has been some struggle with GitHub and pull requests. Do notice the group has been renamed to `sailuh`, so you should update your remote. I don't think anyone claimed it yet, but you don't want to send pull requests elsewhere when someone does.

Typically, doing a `git pull` on your folder should **not* affect your files and sync your repo. I suggest you do so, this time **after putting the files in a safe place as backup so you don't lose your work**. If that fails, then just do a new fork, and copy your files to overwrite the new ones, and send us another pull request. This shouldn't require the main repo any other syncs.

**Review by carlosparadis — CHANGES_REQUESTED** [review]
As we discussed before, could you please re-submit the pull requests with the virtual env. binary being sent on megaupload or drive?

What is the size of the file?

**Review by carlosparadis — APPROVED** [review]

**Comment by carlosparadis** [comment]
Nevermind, I see you modified it so that it is minimal. Thanks!

**Comment by KarishmaGhiya** [comment]
Ok great! Did you need something else? I'm working on this week's tasks. As soon as I'm done I'll update it on Trello.

**Comment by carlosparadis** [comment]
@KarishmaGhiya Nope! All looks great! Just make sure next pull request and commit labels tells a bit more of what you changed for the outside world (I just changed the title of the pull request to reflect that so you can have as an example in replacement of feature 2 and 3). I imagine your next commit label would refer to the .css or what else is written on that checklist! Thanks!

**Comment by carlosparadis** [comment]
@KarishmaGhiya Actually..oops. You sent the sqlite3, not the `virtualenv` to begin with, sorry. Did anything on the virtualenv change, or can I assume the one you sent over e-mail is still current?

**Comment by KarishmaGhiya** [comment]
No changes to the virtual env, it's the same one. It is basically a wrapper and remains the same unless we install some new packages, in which case I'll let you know.

**Comment by carlosparadis** [comment]
@KarishmaGhiya Sounds good! Thanks!

**Pull request merged**
