### PR TITLE
Full Disclosure list graph analysis

### PR DESCRIPTION
**Pull request by jeffgerhard**

### CODE REVIEW

**Review by carlosparadis — CHANGES_REQUESTED** [review]
I need you to make a few changes before we push this into perceive repo: 

- It is usually a bad idea to load images on a version control system (aside from those on the notebook if it needs be). In the case of gephi's images, since we are not using them directly, I suggest that instead you create a mega upload account, host the data there and add an URL pointing to it on your notebook. Make sure that you include the key as part of the URL (if you use the other, it will always prompt the password). 

- Remove opinionated statements that are not towards the analysis (e.g. "Gephi graphs are visually appealing, sophisticated, and relatively easy to use" or "
The result is an attractive graph:", or "We can easily do some basic manipulation and statistics on this graph"). You may pass a bad image that your concern is on making art, or sell the technology you are using rather than analysis (which trust me, it is bad practice in the data science field). 

- Be specific on your claims: For example, you mentioned that "some features of Gephi, and their corresponding plugins, have been dropped from recent versions, while others will benefit from the stronger feature set of a programming language"). You should instead mention what you reported to me earlier in the week of what plugins you tried, what versions, and which failed, and links to the discussion you found on their forums/mailing lists/website stating that was no longer working. This will assist a future student working on this to know the limitations of the tools as new versions come along. Another example is "many graph types caused python to crash. ". Etc. 

- The summary(fd2016) is too cryptic. Either pretty format it or explain in words after the block. 

- I see some typos on the writeup. Use Grammarly to avoid these or some other grammar check. Mine is pointing them out easily for me. 

- The problem statement is missing. Why are we looking on this again? Create a section just for it. 

- Data is missing. Provide the URL I gave you with the data here before you show the graph gif. 

- Explain the graph. What is red, what is blue? Specifically, what is the **graph G = (V,E)** definition? What are the edges weights? 

- Sections should reflect your discussion of the problem, the data model, and the results, rather than "load/run igraph" (move these to within the code blocks as code). Implementation commentary stays within code comments, results discussion stays as text. This facilitates presenting results for audiences interested in results alone, and knowing how you do it! 

- Your next step is running the community detection and betweenness centrality (in fact, this week's actually). Don't worry about plotting. If it needs to be, you can always calculate the centrality and communities, annotate on the network, export it, and load back on Gephi to visualize and interact (in fact, is what a lot of people do!). 

p.s.: It is perfectly fine (and you should) report those as part of your independent study on Trello so we can forward to the professors, just not here.

**Comment by jeffgerhard** [comment]
Thanks for your edits!

**Review by carlosparadis — CHANGES_REQUESTED** [review]
Jeff, can you either revert the commit that sends all these images to the repo, or makes a new pull request? the changes look good but I don't want to overload the main project.

**Comment by jeffgerhard** [comment]
Ok. I am still a little slow at github, I imagine it will be easier to do a new pull request?

**Comment by carlosparadis** [comment]
@jeffgerhard I think so.

**Comment by jeffgerhard** [comment]
Ok I tried a few tactics and maybe this will work for keeping the repo clean? Thanks!

**Pull request closed without merging**
